# Travis performance customizations based on
# http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
# Use faster container-based infrastructure
sudo: false

language: scala

# These directories are cached to S3 at the end of the build
#cache:
#  directories:
#    - $HOME/.ivy2/cache
#    - $HOME/.sbt/boot/

scala:
  - 2.10.5
  - 2.11.8
env:
  # - SPARK_VER=1.6.1 spark 1.6 is not supported anymore
  - SPARK_VER=2.0.2
script:
  - export SKIP_WHEN_TRAVIS=yes; SBT_OPTS="-XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -Xmx4G -XX:MaxPermSize=4G" sbt -Dspark.version=$SPARK_VER -Dscala.version=$TRAVIS_SCALA_VERSION -Dspark.resolver.search=false "set offline := true" test

#  # Tricks to avoid unnecessary cache updates
#  - find $HOME/.sbt -name "*.lock" | xargs rm -f
#  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm -f
